### GET request from the current user
GET http://localhost:8080/api/user/me
Authorization: Bearer {{refreshToken}}

### PUT request to change settings from user
PUT http://localhost:8080/api/user/me
Authorization: Bearer {{refreshToken}}
Content-Type: application/json

{
  "firstName": "Carolin",
  "lastName": "Winter"
}

### GET request to fetch a user by id
@id = 5116e831-ec5a-4127-979a-768ac27b8b2b
GET http://localhost:8080/api/user/{{id}}
Authorization: Bearer {{refreshToken}}

### GET request to search users by username
@username = test
GET http://localhost:8080/api/user/username/{{username}}
Authorization: Bearer {{refreshToken}}

### GET request to search users by email
GET http://localhost:8080/api/user/search?q=
Authorization: Bearer {{refreshToken}}
